ALTER TABLE simulations
  ADD COLUMN IF NOT EXISTS stadium_id VARCHAR(50),
  ADD COLUMN IF NOT EXISTS match_id VARCHAR(20),
  ADD COLUMN IF NOT EXISTS severity VARCHAR(20),
  ADD COLUMN IF NOT EXISTS escalated_from INTEGER REFERENCES simulations(id),
  ADD COLUMN IF NOT EXISTS timeline JSONB DEFAULT '[]'::jsonb;
